# BaseNetProtocol.h

class Protocol:
	commands = {
		# >0 means fixed length
		# <0 means x number of bytes specify length
		1: 5, # NETMSG_KEYFRAME
		2: 1, # NETMSG_NEWFRAME
		3: 1, # NETMSG_QUIT
		4: 5, # NETMSG_STARTPLAYING
		5: 2, # NETMSG_SETPLAYERNUM
		6: -1, # NETMSG_PLAYERNAME
		7: -1, # NETMSG_CHAT
		8: 5, # NETMSG_RANDSEED
		9: 17, # NETMSG_GAMEID
		10: 6, # NETMSG_PATH_CHECKSUM
		11: -2, # NETMSG_COMMAND
		12: -2, # NETMSG_SELECT
		13: 3, # NETMSG_PAUSE
		
		14: -2, # NETMSG_AICOMMAND
		15: -2, # NETMSG_AICOMMANDS
		
		16: -2, # NETMSG_AISHARE
		
		19: 6, # NETMSG_USER_SPEED
		20: 5, # NETMSG_INTERNAL_SPEED
		21: 5, # NETMSG_CPU_USAGE
		22: 2, # NETMSG_DIRECT_CONTROL
		23: 7, # NETMSG_DC_UPDATE
		25: -2, # NETMSG_ATTEMPTCONNECT
		26: 12, # NETMSG_SHARE
		27: 11, # NETMSG_SETSHARE
		28: 1, # NETMSG_SENDPLAYERSTAT
		29: 2 + 0, # NETMSG_PLAYERSTAT # uchar myPlayerNum + sizeof(playerStatistics)
		30: 1, # NETMSG_GAMEOVER
		31: -1, # NETMSG_MAPDRAW
		
		33: 9, # NETMSG_SYNCRESPONSE
		35: -1, # NETMSG_SYSTEMMSG
		36: 16, # NETMSG_STARTPOS
		38: 8, # NETMSG_PLAYERINFO
		39: 3, # NETMSG_PLAYERLEFT
		
		50: -2, # NETMSG_LUAMSG
		51: 5, # NETMSG_TEAM
		52: -2, # NETMSG_GAMEDATA
		
		53: 4, # NETMSG_ALLIANCE
		54: -2, # NETMSG_CCOMAND
		55: 3, # NETMSG_CUSTOM_DATA
		60: 2 + 0, # NETMSG_TEAMSTAT # uchar teamNum + sizeof(CTeam::Statistics)
		
		70: -1, # NETMSG_REQUEST_TEAMSTAT
		
		73: 2, # NETMSG_REGISTER_NETMSG
		74: 2, # NETMSG_UNREGISTER_NETMSG
	}
	
	def __init__(self): pass
	
	def getLength(self, msg_id):
		if not msg_id in self.commands: return 0
		return self.commands[msg_id]

NETWORK_VERSION = 1

# Net Messages

NETMSG_KEYFRAME         = 1
NETMSG_NEWFRAME         = 2
NETMSG_QUIT             = 3
NETMSG_STARTPLAYING     = 4
NETMSG_SETPLAYERNUM     = 5
NETMSG_PLAYERNAME       = 6
NETMSG_CHAT             = 7
NETMSG_RANDSEED         = 8
NETMSG_GAMEID           = 9
NETMSG_PATH_CHECKSUM    = 10
NETMSG_COMMAND          = 11
NETMSG_SELECT           = 12
NETMSG_PAUSE            = 13

NETMSG_AICOMMAND        = 14
NETMSG_AICOMMANDS       = 15


NETMSG_AISHARE          = 16

NETMSG_USER_SPEED       = 19
NETMSG_INTERNAL_SPEED   = 20
NETMSG_CPU_USAGE        = 21
NETMSG_DIRECT_CONTROL   = 22
NETMSG_DC_UPDATE        = 23
NETMSG_ATTEMPTCONNECT   = 25
NETMSG_SHARE            = 26
NETMSG_SETSHARE         = 27
NETMSG_SENDPLAYERSTAT   = 28
NETMSG_PLAYERSTAT       = 29
NETMSG_GAMEOVER         = 30
NETMSG_MAPDRAW          = 31


NETMSG_SYNCRESPONSE     = 33
NETMSG_SYSTEMMSG        = 35
NETMSG_STARTPOS         = 36
NETMSG_PLAYERINFO       = 38
NETMSG_PLAYERLEFT       = 39

NETMSG_LUAMSG           = 50
NETMSG_TEAM             = 51
NETMSG_GAMEDATA         = 52

NETMSG_ALLIANCE         = 53
NETMSG_CCOMMAND         = 54
NETMSG_CUSTOM_DATA      = 55
NETMSG_TEAMSTAT         = 60

NETMSG_AI_CREATED       = 70
NETMSG_AI_STATE_CHANGED = 71

NETMSG_REQUEST_TEAMSTAT = 72

NETMSG_REGISTER_NETMSG	= 73
NETMSG_UNREGISTER_NETMSG= 74

# Data Types for NETMSG_CUSTOM_DATA
CUSTOM_DATA_SPEEDCONTROL = 0
CUSTOM_DATA_LUADRAWTIME = 1

# sub-action types of NETMSG_TEAM

TEAMMSG_GIVEAWAY        = 1
TEAMMSG_RESIGN          = 2
TEAMMSG_JOIN_TEAM       = 3
TEAMMSG_TEAM_DIED       = 4

# sub-action types of NETMSG_MAPDRAW

MAPDRAW_POINT = 1
MAPDRAW_ERASE = 2
MAPDRAW_LINE = 3